const SUPABASE_URL="https://swqaakxywwajesuajflz.supabase.co";
const SUPABASE_KEY="sb_publishable_LfHzOfkinZEd_D8AZpNqCw_075eKf-G";
const API=`${SUPABASE_URL}/rest/v1/date_entries`;
const dataClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{storage:window.sessionStorage,persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});
const content=document.getElementById('detailContent');
function escapeHTML(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function formatDate(v){return v?new Date(`${v}T00:00:00`).toLocaleDateString('en-IN',{day:'numeric',month:'long',year:'numeric'}):''}
function section(label,text,extra=''){if(!text)return '';return `<section class="note-section ${extra}"><div class="note-label">${label}</div><div class="note-text">${escapeHTML(text)}</div></section>`}
async function load(){const id=new URLSearchParams(location.search).get('id');if(!id){content.innerHTML='<div class="error">This memory could not be found. ✿</div>';return}try{const {data:rows,error}=await dataClient.from('date_entries').select('*').eq('id',id).limit(1);if(error)throw error;if(!rows.length)throw new Error('Not found');const d=rows[0];const photos=Array.isArray(d.photo_urls)?d.photo_urls:[];content.innerHTML=`<article class="paper"><header class="paper-header"><div class="paper-kicker">A LITTLE MEMORY OF US ✿</div><h1>${escapeHTML(d.location)}</h1><div class="paper-date">${formatDate(d.date)}</div>${d.occasion?`<div class="occasion">${escapeHTML(d.occasion)}</div>`:''}</header>${section('Description',d.description)}${section('A little detail I remember',d.detail,'detail-highlight')}${section('Favourite moment',d.favourite_moment,'heart-section')}</article><h2 class="photos-title">A few pieces of that day ♡</h2><section class="photos-grid">${photos.length?photos.map((url,i)=>`<div class="photo-frame" style="--rotation:${[-2,1.5,-1,2,-1.5][i%5]}deg"><img src="${escapeHTML(url)}" alt="Photo from ${escapeHTML(d.location)}" loading="lazy"></div>`).join(''):'<div class="empty-photos">The photos for this memory are still waiting to be added. ✿</div>'}</section><p class="footer-note">A day becomes a memory. A memory becomes part of us. ♡</p>`}catch(e){content.innerHTML=`<div class="error">This memory couldn't be opened right now. ✿<br><small>${escapeHTML(e.message)}</small></div>`}}
load();
