const SUPABASE_URL="https://swqaakxywwajesuajflz.supabase.co";
const SUPABASE_KEY="sb_publishable_LfHzOfkinZEd_D8AZpNqCw_075eKf-G";
const API=`${SUPABASE_URL}/rest/v1/date_entries`;
const STORAGE_BUCKET="date-photos";
const PIN="RT2026";
let dates=[];let editing=false;let editingId=null;
const timeline=document.getElementById('timeline');
const addButton=document.getElementById('addDateButton');
const editButton=document.getElementById('editDatesButton');
const modal=document.getElementById('dateModal');
const form=document.getElementById('dateForm');
function headers(extra={}){return {apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,'Content-Type':'application/json',...extra}}
function escapeHTML(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function formatDate(v){if(!v)return '';return new Date(`${v}T00:00:00`).toLocaleDateString('en-IN',{day:'numeric',month:'long',year:'numeric'})}
function openModal(item=null){editingId=item?.id||null;document.getElementById('dateModalTitle').textContent=item?'Edit date':'Add a date';document.getElementById('locationInput').value=item?.location||'';document.getElementById('occasionInput').value=item?.occasion||'';document.getElementById('dateInput').value=item?.date||'';document.getElementById('descriptionInput').value=item?.description||'';document.getElementById('detailInput').value=item?.detail||'';document.getElementById('favouriteInput').value=item?.favourite_moment||'';document.querySelectorAll('.photo-input').forEach(x=>x.value='');document.getElementById('formStatus').textContent='';modal.classList.add('open');modal.setAttribute('aria-hidden','false')}
function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');form.reset();editingId=null}
async function loadDates(){try{const r=await fetch(`${API}?select=*&order=date.desc,created_at.desc`,{headers:headers()});if(!r.ok)throw new Error(await r.text());dates=await r.json();render()}catch(e){timeline.innerHTML=`<div class="empty-state">Our memories couldn't be loaded right now.<br><small>${escapeHTML(e.message)}</small></div>`}}
function render(){if(!dates.length){timeline.innerHTML='<div class="empty-state">Our garden is waiting for its first date. ✿<br>Unlock editing to add a memory.</div>';return}timeline.classList.toggle('editing',editing);timeline.innerHTML=dates.map(item=>`<article class="timeline-item"><a class="timeline-card" href="date-detail.html?id=${encodeURIComponent(item.id)}"><div class="timeline-location">${escapeHTML(item.location)}</div><div class="timeline-date">${formatDate(item.date)}</div></a><div class="timeline-edit"><button class="mini-button edit-date" data-id="${item.id}">Edit</button><button class="mini-button delete-date" data-id="${item.id}">Delete</button></div></article>`).join('');document.querySelectorAll('.edit-date').forEach(b=>b.addEventListener('click',()=>openModal(dates.find(x=>x.id===b.dataset.id))));document.querySelectorAll('.delete-date').forEach(b=>b.addEventListener('click',()=>deleteDate(b.dataset.id)))}
async function deleteDate(id){if(!confirm('Delete this date memory?'))return;const r=await fetch(`${API}?id=eq.${encodeURIComponent(id)}`,{method:'DELETE',headers:headers({'Prefer':'return=minimal'})});if(!r.ok){alert('Could not delete this memory. Check the Supabase DELETE policy.');return}dates=dates.filter(x=>x.id!==id);render()}
async function uploadPhotos(dateId){const files=[...document.querySelectorAll('.photo-input')].map(x=>x.files[0]).filter(Boolean);if(!files.length)return[];const urls=[];for(let i=0;i<files.length&&i<5;i++){const file=files[i];if(!file.type.startsWith('image/'))throw new Error('Please select image files only.');if(file.size>8*1024*1024)throw new Error('Each photo must be below 8 MB.');const safe=file.name.toLowerCase().replace(/[^a-z0-9.]+/g,'-');const path=`${dateId}/${Date.now()}-${i}-${safe}`;const r=await fetch(`${SUPABASE_URL}/storage/v1/object/${STORAGE_BUCKET}/${path}`,{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,'x-upsert':'false','Content-Type':file.type},body:file});if(!r.ok)throw new Error(await r.text());urls.push(`${SUPABASE_URL}/storage/v1/object/public/${STORAGE_BUCKET}/${path}`)}return urls}
form.addEventListener('submit',async e=>{e.preventDefault();const status=document.getElementById('formStatus'),save=document.getElementById('saveDateButton');const payload={location:document.getElementById('locationInput').value.trim(),occasion:document.getElementById('occasionInput').value.trim()||null,date:document.getElementById('dateInput').value,description:document.getElementById('descriptionInput').value.trim()||null,detail:document.getElementById('detailInput').value.trim()||null,favourite_moment:document.getElementById('favouriteInput').value.trim()||null,updated_at:new Date().toISOString()};if(!payload.location||!payload.date)return;save.disabled=true;status.textContent='Saving our memory…';try{let id=editingId;if(id){let r=await fetch(`${API}?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:headers({'Prefer':'return=minimal'}),body:JSON.stringify(payload)});if(!r.ok)throw new Error(await r.text())}else{payload.display_order=dates.length;let r=await fetch(API,{method:'POST',headers:headers({'Prefer':'return=representation'}),body:JSON.stringify(payload)});if(!r.ok)throw new Error(await r.text());const created=await r.json();id=created[0].id}const newUrls=await uploadPhotos(id);if(newUrls.length){const existing=dates.find(x=>x.id===id)?.photo_urls||[];const merged=[...existing,...newUrls].slice(0,5);let r=await fetch(`${API}?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:headers({'Prefer':'return=minimal'}),body:JSON.stringify({photo_urls:merged,updated_at:new Date().toISOString()})});if(!r.ok)throw new Error(await r.text())}closeModal();await loadDates()}catch(err){status.textContent='Could not save: '+err.message}finally{save.disabled=false}});
editButton.addEventListener('click',()=>{if(editing){editing=false;addButton.hidden=true;editButton.textContent='🔒 Edit dates';render();return}const entered=prompt('Enter the editing PIN:');if(entered===PIN){editing=true;addButton.hidden=false;editButton.textContent='🔓 Lock editing';render()}else if(entered!==null)alert("That PIN doesn't match.")});addButton.addEventListener('click',()=>openModal());document.querySelectorAll('[data-close-modal]').forEach(x=>x.addEventListener('click',closeModal));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});loadDates();
